---
title: "Day 3 R"
author: "Rachel Rosenberg"
date: "9/19/2018"
output: html_document
---

## Learning dplyr - working with California Energy dataset

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import data

```{r}
generation <- read.csv(here::here("data","generation.csv"), stringsAsFactors = F)
imports <- read.csv(here::here("data","imports.csv"), stringsAsFactors = F)

str(generation)
str(imports)
# we mostly have numeric variables and integers. descriptive column names. 
# datetime listed as yr/mo/day and hr:min:sec. want to convert to datetime

```

## Recode datetime variable as datetime class

```{r}
library(lubridate)
generation$datetime <- as_datetime(generation$datetime)
class(generation$datetime)
head(generation$datetime)

imports$datetime <- as_datetime(imports$datetime)
class(imports$datetime)
head(imports$datetime)
```

## Reshape data

```{r}
library(reshape2)
long_gen <- melt(generation, id.vars = "datetime",
                  variable.name = "source",
                  value.name = "usage")
head(long_gen)
long_gen[order(long_gen$datetime)[1:20], ]
```

## Merging Data
 
```{r}
merged_energy <- merge(generation, imports, by = "datetime")
dim(merged_energy)
head(merged_energy)
```

## Reshape (melt) the merged data

```{r}
long_merged_energy <- melt(merged_energy, id.vars = "datetime", variable.name = "source", value.name = "usage")
head(long_merged_energy)
str(long_merged_energy)
```

## Introducing dplyr for analysis
## Dplyr verbs

```{r}
# import
library(dplyr)

# select
tmp <- select(merged_energy, biogas, biomass, geothermal, solar)
names(tmp)
tmp <- select(merged_energy, -biogas, -biomass, -geothermal, -solar)
names(tmp)
tmp <- select(merged_energy, contains("hydro"), starts_with("bio"))
names(tmp)

# filter
tmp <- filter(merged_energy, imports > 7000, natural_gas < 7000)
nrow(tmp)
head(tmp)

# mutate - creates new vars
tmp<- mutate(long_merged_energy, log_usage = log(usage))
head(tmp)
tmp<- mutate(long_merged_energy, log_usage = log(usage), usage2 <- usage^2, usage3 <- usage^3)
head(tmp)

# summarize
tmp <- summarise(long_merged_energy, total = sum(usage, na.rm = T))
head(tmp)
tmp <- summarise(long_merged_energy, mean_cons = mean(usage, na.rm = T))
head(tmp)
```

## The Pipe Operator

```{r}
# take df then filter it, then select these variables. no need to repeat df name!
# recall that dfs created during this pipe do not exist in the global environment
long_merged_energy %>%
  filter(source == "geothermal") %>%
  select(-datetime) %>%
  mutate(log_usage = log(usage), na.rm = T) %>%
  summarize(mean_log_usage = mean(log_usage, na.rm = T))

# use the . to denote the changed df.
# here, we find the row sums of the columns in the new implicit (manipulated) df
merged_energy %>%
  select(-datetime) %>%
  mutate(total_usage = rowSums(., na.rm = T)) %>%
  summarize(total_usage = sum(total_usage, na.rm = T))

merged_energy %>%
  select(contains("hydro")) %>%
  mutate(total_hydro = rowSums(., na.rm = T)) %>%
  summarize(mean_hydro = mean(total_hydro, na.rm = T))
```

## Group By

```{r}
long_merged_energy %>%
  group_by(source) %>%
  summarize(sum_usage = sum(usage, na.rm = T))

# back to gapminder dataset
gapminder <- read.csv(here::here("data", "gapminder5.csv"))

gapminder %>%
  group_by(year) %>%
  summarize(mean_le = mean(lifeExp, na.rm = T), sd_le = sd(lifeExp, na.rm = T))
```

## Find the mean by hour using dplyr

```{r}
# Find the mean usage for small hydro, large hydro, bio gas, and biomass

merged_energy %>%
  select(contains("datetime"), contains("bio"), contains("hydro")) %>%
  melt(., id.vars = "datetime", variable.name = "source", value.name = "usage") %>%
  group_by(source) %>%
  summarize(mean_usage = mean(usage, na.rm = T))
  
```

